### PR TITLE
1st develop

### PR DESCRIPTION
**Pull request by wangzhao0217**
- add  .devcontainer
- adding pkgs
- add parameters.json and add cohesive_network_prep function
- adding funtions
- remove copied functions
- cohesive_network_prep checked
- funtion check done, need to prepare examples

### CODE REVIEW

**Comment by Robinlovelace** [comment]
OK let's look at this now!

**Review by Robinlovelace — CHANGES_REQUESTED** [review]
Looks like tests are failing:

https://github.com/nptscot/corenet/actions/runs/8941789200/job/24562932568#step:6:142

You need to document and add the object with `usethis::use_data(NPT_demo_3km)` for this minimal dataset to be added to the `data/` folder. Or you could start the example by reading-in the dataset from somewhere online.

**Comment by wangzhao0217** [comment]
Hi Robin, the check is passed. ready to merge to main!

**Comment by Robinlovelace** [comment]
Try following these instructions from inside the container and then committing/pushing from PowerShell? 

https://stackoverflow.com/questions/33450269/how-to-search-and-remove-m-in-all-files-in-a-directory-recursively

**Pull request merged**
