### PR TITLE
optimize

### PR DESCRIPTION
**Pull request by wangzhao0217**
- remove lines
- update weight cal
- update
- update parameters

### CODE REVIEW

**Review by Robinlovelace — COMMENTED** [review]
Great job Zhao!

**Comment by Robinlovelace** [comment]
How do the new results look?

**Comment by wangzhao0217** [comment]
Hi Robin, the pathfinder logic has definitely improved. Here are the preliminary CN results, including links between LAs. How does it look?
image

**Comment by Robinlovelace** [comment]
Looks great. First thought: maybe too many links in sparsely populated areas, do we need so many connections to Edinburgh for example? Overally: much better, impressive improvement :tada: key thing is what Angus thinks, hopefully he'll be happy :smile:

**Comment by Robinlovelace** [comment]
:+1:

**Pull request merged**
